<?php

namespace Database\Seeders;

use App\Models\Etudiant;
use App\Models\Classe;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class EtudiantsSeeder extends Seeder
{
    /** Typical age at the start of each Mauritanian level. */
    private const LEVEL_AGE = [
        '1AF' => 6, '2AF' => 7, '3AF' => 8, '4AF' => 9, '5AF' => 10, '6AF' => 11,
        '1AS' => 12, '2AS' => 13, '3AS' => 14, '4AS' => 15,
        '5AS' => 16, '6AS' => 17, '7AS' => 18,
    ];

    public function run(): void
    {
        $classes = Classe::all();

        if ($classes->isEmpty()) {
            $this->command->warn('No classes found. Run ClassesSeeder first.');
            return;
        }

        foreach ($classes as $classe) {
            $count = rand(12, 18); // ~15 students per group

            for ($i = 0; $i < $count; $i++) {
                $genre = rand(1, 2) === 1 ? 'M' : 'F';
                $nom = $this->getRandomMauritanianLastName();
                $prenom = $this->getRandomMauritanianFirstName($genre);

                // Avoid duplicates within the same group.
                if (Etudiant::where('nom', $nom)->where('prenom', $prenom)->where('id_classe', $classe->id_classe)->exists()) {
                    continue;
                }

                $etudiant = Etudiant::create([
                    'nom' => $nom,
                    'prenom' => $prenom,
                    'telephone' => $this->generatePhoneNumber(),
                    'adresse' => $this->getRandomAddress(),
                    'date_naissance' => $this->birthDateForLevel($classe->niveau),
                    'genre' => $genre,
                    'id_classe' => $classe->id_classe,
                    // matricule auto-generated by the model
                ]);

                // Only older (lycée) students get a login account — ~30%.
                if ($classe->cycle === 'lycee' && rand(1, 100) <= 30) {
                    $email = $this->ensureUniqueEmail(
                        strtolower($prenom) . '.' . strtolower(str_replace(' ', '', $nom)) . '@student.ecole.com'
                    );

                    $user = User::create([
                        'name' => trim($prenom . ' ' . $nom),
                        'email' => $email,
                        'password' => Hash::make('student123'),
                        'is_active' => rand(1, 100) <= 90,
                        'email_verified_at' => now(),
                        'profile_type' => Etudiant::class,
                        'profile_id' => $etudiant->id_etudiant,
                    ]);

                    $user->assignRole('student');
                }
            }
        }

        $this->command->info(Etudiant::count() . ' students seeded.');
    }

    private function birthDateForLevel(string $niveau): string
    {
        $age = self::LEVEL_AGE[$niveau] ?? 12;
        $birthYear = (int) date('Y') - $age + rand(-1, 1);

        return sprintf('%d-%02d-%02d', $birthYear, rand(1, 12), rand(1, 28));
    }

    private function getRandomMauritanianFirstName(string $genre): string
    {
        $maleNames = [
            'Mohamed', 'Ahmed', 'Sidi', 'Oumar', 'Abdallahi', 'Mohamed Lemine', 'Salem', 'Mahmoud',
            'Amadou', 'Ousmane', 'Ibrahim', 'Youssef', 'Hassan', 'Moctar', 'Cheikh', 'Brahim',
            'Moustapha', 'Sid Ahmed', 'Mohamed Vall', 'Ely', 'Yahya', 'Isselmou',
        ];

        $femaleNames = [
            'Fatimata', 'Aissata', 'Mariem', 'Khadija', 'Aminetou', 'Aïcha', 'Khadijetou',
            'Maryam', 'Coumba', 'Zeynab', 'Habiba', 'Selma', 'Rokia', 'Safiatou',
            'Nana', 'Maimouna', 'Hawwa',
        ];

        return $genre === 'M' ? $maleNames[array_rand($maleNames)] : $femaleNames[array_rand($femaleNames)];
    }

    private function getRandomMauritanianLastName(): string
    {
        $lastNames = [
            'Ould Ahmed', 'Mint Sidi', 'Ba', 'Sy', 'Kane', 'Diallo', 'Ould Baba', 'Mint Vall',
            'Ould Mohamed', 'Mint Ebnou', 'Ould Abdallahi', 'Mint Mohamedou', 'Touré', 'Sow',
            'Ould Salem', 'Mint Ahmed', 'Camara', 'Traoré', 'Ould Cheikh', 'Mint Moctar',
            'Ould Brahim', 'Mint Yahya', 'Ould Sid Ahmed', 'Mint Isselmou', 'Yall', 'Thiam',
        ];

        return $lastNames[array_rand($lastNames)];
    }

    private function getRandomAddress(): string
    {
        $neighborhoods = [
            'Tevragh Zeina', 'Ksar', 'El Mina', 'Sebkha', 'Arafat', 'Toujounine',
            'Dar Naim', 'Riad', 'Hay Saken', 'Medina',
        ];

        return $neighborhoods[array_rand($neighborhoods)] . ', Secteur ' . rand(1, 20) . ', Nouakchott';
    }

    private function generatePhoneNumber(): string
    {
        $prefixes = ['30', '31', '32', '33', '34', '36', '37', '38', '39'];
        $prefix = $prefixes[array_rand($prefixes)];

        return '+222 ' . $prefix . ' ' . sprintf('%02d %02d %02d', rand(10, 99), rand(10, 99), rand(10, 99));
    }

    private function ensureUniqueEmail(string $email): string
    {
        $original = $email;
        $counter = 1;

        while (User::where('email', $email)->exists()) {
            $email = str_replace('@', $counter . '@', $original);
            $counter++;
        }

        return $email;
    }
}
