<?php

namespace App\Filament\Imports;

use App\Models\Classe;
use App\Models\Etudiant;
use Filament\Actions\Imports\ImportColumn;
use Filament\Actions\Imports\Importer;
use Filament\Actions\Imports\Models\Import;
use Illuminate\Support\Number;

class EtudiantImporter extends Importer
{
    protected static ?string $model = Etudiant::class;

    public static function getColumns(): array
    {
        return [
            ImportColumn::make('nom')
                ->label(__('app.nom'))
                ->requiredMapping()
                ->rules(['required', 'max:191']),
            ImportColumn::make('prenom')
                ->label(__('app.prenom'))
                ->requiredMapping()
                ->rules(['required', 'max:191']),
            ImportColumn::make('genre')
                ->label(__('app.genre'))
                ->requiredMapping()
                ->rules(['required', 'in:M,F']),
            ImportColumn::make('date_naissance')
                ->label(__('app.date_naissance'))
                ->requiredMapping()
                ->rules(['required', 'date']),
            ImportColumn::make('telephone')
                ->label(__('app.telephone'))
                ->rules(['max:191']),
            ImportColumn::make('adresse')
                ->label(__('app.adresse'))
                ->rules(['max:191']),
            // Match the class by its code (e.g. 1AS-G1) or its stored name.
            ImportColumn::make('classe')
                ->label(__('app.classe'))
                ->requiredMapping()
                ->relationship(resolveUsing: function (string $state): ?Classe {
                    return Classe::all()->first(
                        fn (Classe $c) => $c->code === $state || $c->nom_classe === $state
                    );
                })
                ->rules(['required']),
            // matricule is auto-generated by the model on create.
        ];
    }

    public function resolveRecord(): Etudiant
    {
        return new Etudiant();
    }

    public static function getCompletedNotificationBody(Import $import): string
    {
        $body = 'Your etudiant import has completed and ' . Number::format($import->successful_rows) . ' ' . str('row')->plural($import->successful_rows) . ' imported.';

        if ($failedRowsCount = $import->getFailedRowsCount()) {
            $body .= ' ' . Number::format($failedRowsCount) . ' ' . str('row')->plural($failedRowsCount) . ' failed to import.';
        }

        return $body;
    }
}
